apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flask-api
  name: flask-api
  labels:
    app: flask-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: 401602556575.dkr.ecr.us-east-2.amazonaws.com/flask-demo/flask-api:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /v1
            port: 5000
          initialDelatySeconds: 3
          periodSeconds: 5